# Generated by Django 4.1.5 on 2023-03-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='Lastname',
        ),
    ]
