# Generated by Django 4.1.5 on 2023-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patientdata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')])),
            ],
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Gender',
        ),
    ]
