# Generated by Django 4.1.5 on 2023-03-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_remove_patientdata_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
