# Generated by Django 4.1.5 on 2023-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_patientdata_delete_patientdata2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='Date',
            field=models.DateField(),
        ),
    ]
