# Generated by Django 4.1.5 on 2023-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_patientdata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patientdata',
        ),
    ]
