# Generated by Django 4.1.5 on 2023-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_patientdata2_delete_patientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (1, 'NOT SPECIFIED')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Gender2', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patientdata2',
        ),
    ]
