# Generated by Django 4.1.5 on 2023-03-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_patient_patientdata_delete_patientdata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Gender2',
        ),
    ]
