# Generated by Django 4.1.5 on 2023-03-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bookdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='Appointmentdate',
            new_name='adate',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='Dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookdata',
            old_name='Reason',
            new_name='visit',
        ),
    ]
