# Generated by Django 4.0.6 on 2023-03-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_bookdata2_name_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
