# Generated by Django 4.0.6 on 2023-03-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pateintlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Otp', models.IntegerField(max_length=30)),
            ],
        ),
    ]
