# Generated by Django 4.0.6 on 2023-03-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_pateintlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateintlogin',
            name='Otp',
            field=models.CharField(max_length=30),
        ),
    ]
