# Generated by Django 4.0.6 on 2023-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_pateintlogin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pateintlogin',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
