# Generated by Django 4.0.6 on 2023-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_pateintlogin_is_varified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.IntegerField(max_length=10)),
            ],
        ),
    ]
