# Generated by Django 4.0.6 on 2023-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_doctor_log_alter_admin_log_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement_md',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=20)),
                ('Announce', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
