# Generated by Django 4.0.6 on 2023-03-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_announcement_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement_md',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
