# Generated by Django 4.0.6 on 2023-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_paymentdata_delete_paymentdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Medicine', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
