# Generated by Django 4.0.6 on 2023-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_prescriptiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptiondata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Medicine', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patientdata2',
        ),
        migrations.DeleteModel(
            name='Prescriptiondata',
        ),
    ]
