# Generated by Django 4.0.6 on 2023-04-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_patientdata_prescriptiondata23_delete_patientdata1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_log1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement_md1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Announce', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('visit', models.CharField(max_length=50)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_log1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pateintlogin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Otp', models.CharField(max_length=30)),
                ('is_varified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patientdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paymentdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Cvv', models.IntegerField(max_length=3)),
                ('Card', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('Otp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptiondata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Medicine', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_log',
        ),
        migrations.DeleteModel(
            name='Announcement_md',
        ),
        migrations.DeleteModel(
            name='Bookdata',
        ),
        migrations.DeleteModel(
            name='Doctor_log',
        ),
        migrations.DeleteModel(
            name='Pateintlogin',
        ),
        migrations.DeleteModel(
            name='Patientdata',
        ),
        migrations.DeleteModel(
            name='Paymentdata',
        ),
        migrations.DeleteModel(
            name='Prescriptiondata23',
        ),
    ]
